services:
  pg2:
    image: postgres
    environment:
      POSTGRES_DB: backendchats
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    ports:
      - "5222:5432"
  app:

    env_file:
        - fastapi-chat/.env.template
    build:
      dockerfile: ./docker-build/Dockerfile
      context: ./
    ports:
      - "8000:8000"
      
    
